
ODIR=obj
IDIR=src include
VPATH=src
_OBJ =image_DXT.o image_helper.o SOIL.o stb_image_aug.o


#_OBJ += TestAlgebraicCircleFits.opp
#target_bin=TestAlgebraicCircleFits
target_a=SOIL.a

 
FLAGS= -w -O3 -Wnoc++11-narrowing
include $(MakeTemplate)
