
target_bin = main
_OBJ = main.opp



# export MODULE_libxd=$(abspath ../libxd-0.3.2)



# IDIR=	include/ \
# 			$(MODULE_libxd)/include/ 
# EXT_OBJS= $(MODULE_libxd)/lib/libglad.a \
# 	$(MODULE_libxd)/lib/libxd.a \
# 	$(MODULE_libxd)/lib/libglfw3.a \

export FLAGS= -w -O3 -std=c++0x

export MakeTemplate:= Makefile.in
include $(MakeTemplate)
