
TOOLCHAIN_DIR=/c/SysGCC/raspberry/
SYSROOT_FLAG=
TOOLCHAIN_PREFIX=${TOOLCHAIN_DIR}/bin/arm-linux-gnueabihf-
export CC=${TOOLCHAIN_PREFIX}gcc.exe $SYSROOT_FLAG
export CXX=${TOOLCHAIN_PREFIX}g++.exe $SYSROOT_FLAG
export AR=${TOOLCHAIN_PREFIX}ar.exe $SYSROOT_FLAG

make
