
target_bin=TestAlgebraicCircleFits
ODIR=obj
IDIR=
_OBJ = circle.opp data.opp \
       CircleFitByHyper.opp \
       CircleFitByKasa.opp \
       CircleFitByPratt.opp \
       CircleFitByTaubin.opp \
       Utilities.opp \
       TestAlgebraicCircleFits.opp

export FLAGS= -w
include $(MakeTemplate)
