
target_a=CircleFits.a
ODIR=obj
IDIR=
_OBJ = circle.opp data.opp \
       CircleFitByHyper.opp \
       CircleFitByKasa.opp \
       CircleFitByPratt.opp \
       CircleFitByTaubin.opp \
       Utilities.opp


#_OBJ += TestAlgebraicCircleFits.opp
#target_bin=TestAlgebraicCircleFits
target_a=CircleFitting.a

include $(MakeTemplate)
