# PlatformIO pre-script: stamp the build with its git identity and build time.
#
# The board could always answer get_version, but with a hand-maintained "0.0.1"
# that says nothing about WHICH build is flashed. That gap cost real time: the
# auto-slowdown (PLATE_FREQ_SETPOINT*=19/20) was commented out in the source on
# 2026-08-01, and there was no way to tell from the board whether the chip in
# front of us predated that. Source truth and flashed truth are different facts;
# this makes the second one askable.
#
# The values go into a GENERATED SOURCE FILE, not into CPPDEFINES.
#
# The first version of this script appended -DFW_BUILD_TIME=... to the global
# build flags. The timestamp differs on every run, so the build signature
# differed on every run, so EVERY translation unit recompiled every time --
# measured: MachineConfig.cpp.o, which uses neither macro and had not been
# edited, rebuilt during a plain upload. One generated file costs one small
# recompile plus the link, which is the irreducible price of embedding a
# timestamp at all.
import os
import subprocess
import datetime

Import("env")  # noqa: F821  (SCons injects this)

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821


def _git(*args, default="unknown"):
    try:
        out = subprocess.run(
            ["git"] + list(args),
            cwd=PROJECT_DIR,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if out.returncode != 0:
            return default
        return out.stdout.strip() or default
    except Exception:
        # No git, no repo, no git in PATH -- a build that cannot name itself is
        # still a build. Never fail the compile over provenance.
        return default


git_hash = _git("rev-parse", "--short=12", "HEAD")
# A dirty tree means the flashed image is NOT the commit it names, which is
# exactly the case where trusting the hash misleads. Say so in the hash itself.
if _git("status", "--porcelain", default=""):
    git_hash += "-dirty"

# Local time, seconds resolution, no timezone suffix: this is read by a human
# comparing against a git log line, not parsed by a machine. It is the time the
# image was COMPILED -- firmware cannot know when it will be flashed.
build_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def _c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


gen_path = os.path.join(PROJECT_DIR, "src", "fw_version_gen.c")
body = (
    "/* GENERATED by tools/fw_version.py at build time. Do not edit. */\n"
    '#include "fw_version.h"\n'
    "const char *const FW_GIT_HASH   = %s;\n"
    "const char *const FW_BUILD_TIME = %s;\n"
) % (_c_string(git_hash), _c_string(build_time))

old = None
if os.path.exists(gen_path):
    with open(gen_path, encoding="utf-8") as fh:
        old = fh.read()
if old != body:
    with open(gen_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)

print("fw_version: git %s  built %s" % (git_hash, build_time))
