
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>
            #include <arvapi.h>

            G_BEGIN_DECLS

/* enumerations from "arvbuffer.h" */

ARV_API
GType arv_buffer_status_get_type (void);
#define ARV_TYPE_BUFFER_STATUS (arv_buffer_status_get_type())

ARV_API
GType arv_buffer_payload_type_get_type (void);
#define ARV_TYPE_BUFFER_PAYLOAD_TYPE (arv_buffer_payload_type_get_type())

/* enumerations from "arvchunkparser.h" */

ARV_API
GType arv_chunk_parser_error_get_type (void);
#define ARV_TYPE_CHUNK_PARSER_ERROR (arv_chunk_parser_error_get_type())

/* enumerations from "arvdevice.h" */

ARV_API
GType arv_device_error_get_type (void);
#define ARV_TYPE_DEVICE_ERROR (arv_device_error_get_type())

/* enumerations from "arvdomnode.h" */

ARV_API
GType arv_dom_node_type_get_type (void);
#define ARV_TYPE_DOM_NODE_TYPE (arv_dom_node_type_get_type())

/* enumerations from "arvenums.h" */

ARV_API
GType arv_auto_get_type (void);
#define ARV_TYPE_AUTO (arv_auto_get_type())

ARV_API
GType arv_acquisition_mode_get_type (void);
#define ARV_TYPE_ACQUISITION_MODE (arv_acquisition_mode_get_type())

ARV_API
GType arv_exposure_mode_get_type (void);
#define ARV_TYPE_EXPOSURE_MODE (arv_exposure_mode_get_type())

ARV_API
GType arv_uv_usb_mode_get_type (void);
#define ARV_TYPE_UV_USB_MODE (arv_uv_usb_mode_get_type())

/* enumerations from "arvgc.h" */

ARV_API
GType arv_gc_error_get_type (void);
#define ARV_TYPE_GC_ERROR (arv_gc_error_get_type())

ARV_API
GType arv_register_cache_policy_get_type (void);
#define ARV_TYPE_REGISTER_CACHE_POLICY (arv_register_cache_policy_get_type())

ARV_API
GType arv_range_check_policy_get_type (void);
#define ARV_TYPE_RANGE_CHECK_POLICY (arv_range_check_policy_get_type())

ARV_API
GType arv_access_check_policy_get_type (void);
#define ARV_TYPE_ACCESS_CHECK_POLICY (arv_access_check_policy_get_type())

/* enumerations from "arvgcenums.h" */

ARV_API
GType arv_gc_name_space_get_type (void);
#define ARV_TYPE_GC_NAME_SPACE (arv_gc_name_space_get_type())

ARV_API
GType arv_gc_access_mode_get_type (void);
#define ARV_TYPE_GC_ACCESS_MODE (arv_gc_access_mode_get_type())

ARV_API
GType arv_gc_cachable_get_type (void);
#define ARV_TYPE_GC_CACHABLE (arv_gc_cachable_get_type())

ARV_API
GType arv_gc_signedness_get_type (void);
#define ARV_TYPE_GC_SIGNEDNESS (arv_gc_signedness_get_type())

ARV_API
GType arv_gc_is_linear_get_type (void);
#define ARV_TYPE_GC_IS_LINEAR (arv_gc_is_linear_get_type())

ARV_API
GType arv_gc_visibility_get_type (void);
#define ARV_TYPE_GC_VISIBILITY (arv_gc_visibility_get_type())

ARV_API
GType arv_gc_representation_get_type (void);
#define ARV_TYPE_GC_REPRESENTATION (arv_gc_representation_get_type())

ARV_API
GType arv_gc_display_notation_get_type (void);
#define ARV_TYPE_GC_DISPLAY_NOTATION (arv_gc_display_notation_get_type())

ARV_API
GType arv_gc_streamable_get_type (void);
#define ARV_TYPE_GC_STREAMABLE (arv_gc_streamable_get_type())

/* enumerations from "arvgcpropertynode.h" */

ARV_API
GType arv_gc_property_node_type_get_type (void);
#define ARV_TYPE_GC_PROPERTY_NODE_TYPE (arv_gc_property_node_type_get_type())

/* enumerations from "arvgvdevice.h" */

ARV_API
GType arv_gv_packet_size_adjustment_get_type (void);
#define ARV_TYPE_GV_PACKET_SIZE_ADJUSTMENT (arv_gv_packet_size_adjustment_get_type())

ARV_API
GType arv_gv_ip_configuration_mode_get_type (void);
#define ARV_TYPE_GV_IP_CONFIGURATION_MODE (arv_gv_ip_configuration_mode_get_type())

/* enumerations from "arvgvstream.h" */

ARV_API
GType arv_gv_stream_option_get_type (void);
#define ARV_TYPE_GV_STREAM_OPTION (arv_gv_stream_option_get_type())

ARV_API
GType arv_gv_stream_socket_buffer_get_type (void);
#define ARV_TYPE_GV_STREAM_SOCKET_BUFFER (arv_gv_stream_socket_buffer_get_type())

ARV_API
GType arv_gv_stream_packet_resend_get_type (void);
#define ARV_TYPE_GV_STREAM_PACKET_RESEND (arv_gv_stream_packet_resend_get_type())

/* enumerations from "arvstream.h" */

ARV_API
GType arv_stream_callback_type_get_type (void);
#define ARV_TYPE_STREAM_CALLBACK_TYPE (arv_stream_callback_type_get_type())

/* enumerations from "arvxmlschema.h" */

ARV_API
GType arv_xml_schema_error_get_type (void);
#define ARV_TYPE_XML_SCHEMA_ERROR (arv_xml_schema_error_get_type())

G_END_DECLS

/* Generated data ends here */

