
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>


            G_BEGIN_DECLS

/* enumerations from "arvdebugprivate.h" */


GType arv_debug_level_get_type (void);
#define ARV_TYPE_DEBUG_LEVEL (arv_debug_level_get_type())


GType arv_debug_category_get_type (void);
#define ARV_TYPE_DEBUG_CATEGORY (arv_debug_category_get_type())

/* enumerations from "arvgcconverterprivate.h" */


GType arv_gc_converter_node_type_get_type (void);
#define ARV_TYPE_GC_CONVERTER_NODE_TYPE (arv_gc_converter_node_type_get_type())

/* enumerations from "arvgvcpprivate.h" */


GType arv_gvcp_packet_type_get_type (void);
#define ARV_TYPE_GVCP_PACKET_TYPE (arv_gvcp_packet_type_get_type())


GType arv_gvcp_error_get_type (void);
#define ARV_TYPE_GVCP_ERROR (arv_gvcp_error_get_type())


GType arv_gvcp_cmd_packet_flags_get_type (void);
#define ARV_TYPE_GVCP_CMD_PACKET_FLAGS (arv_gvcp_cmd_packet_flags_get_type())


GType arv_gvcp_event_packet_flags_get_type (void);
#define ARV_TYPE_GVCP_EVENT_PACKET_FLAGS (arv_gvcp_event_packet_flags_get_type())


GType arv_gvcp_discovery_packet_flags_get_type (void);
#define ARV_TYPE_GVCP_DISCOVERY_PACKET_FLAGS (arv_gvcp_discovery_packet_flags_get_type())


GType arv_gvcp_command_get_type (void);
#define ARV_TYPE_GVCP_COMMAND (arv_gvcp_command_get_type())

/* enumerations from "arvgvspprivate.h" */


GType arv_gvsp_packet_type_get_type (void);
#define ARV_TYPE_GVSP_PACKET_TYPE (arv_gvsp_packet_type_get_type())


GType arv_gvsp_content_type_get_type (void);
#define ARV_TYPE_GVSP_CONTENT_TYPE (arv_gvsp_content_type_get_type())


GType arv_gvsp_payload_type_get_type (void);
#define ARV_TYPE_GVSP_PAYLOAD_TYPE (arv_gvsp_payload_type_get_type())

/* enumerations from "arvuvcpprivate.h" */


GType arv_uvcp_status_get_type (void);
#define ARV_TYPE_UVCP_STATUS (arv_uvcp_status_get_type())


GType arv_uvcp_flags_get_type (void);
#define ARV_TYPE_UVCP_FLAGS (arv_uvcp_flags_get_type())


GType arv_uvcp_command_get_type (void);
#define ARV_TYPE_UVCP_COMMAND (arv_uvcp_command_get_type())


GType arv_uvcp_manifest_schema_type_get_type (void);
#define ARV_TYPE_UVCP_MANIFEST_SCHEMA_TYPE (arv_uvcp_manifest_schema_type_get_type())

/* enumerations from "arvuvdeviceprivate.h" */


GType arv_uv_endpoint_type_get_type (void);
#define ARV_TYPE_UV_ENDPOINT_TYPE (arv_uv_endpoint_type_get_type())

/* enumerations from "arvuvspprivate.h" */


GType arv_uvsp_packet_type_get_type (void);
#define ARV_TYPE_UVSP_PACKET_TYPE (arv_uvsp_packet_type_get_type())


GType arv_uvsp_payload_type_get_type (void);
#define ARV_TYPE_UVSP_PAYLOAD_TYPE (arv_uvsp_payload_type_get_type())

G_END_DECLS

/* Generated data ends here */

