



IDIR=./include/ \
			$(MODULE_cJSON) \
			$(MODULE_acvImage)/include

ODIR=obj
_OBJ = VisSeleDefineDocParser.opp

target_a= VisSeleDefineDocParser.a \
					$(MODULE_cJSON)/cJSON.a \

include ../Makefile.in
