# Generates build_info.h with git + timestamp provenance. Run at BUILD time (via a
# custom target) so the hash/time reflect the actual build, not just configure.
#   cmake -DOUT=<path> -DCFG=<config> -DSRC=<source_dir> -P gen_build_info.cmake
if(NOT DEFINED OUT)
  message(FATAL_ERROR "gen_build_info: -DOUT required")
endif()
if(NOT DEFINED SRC)
  set(SRC "${CMAKE_CURRENT_LIST_DIR}/..")
endif()

find_package(Git QUIET)
set(GIT_HASH "unknown")
set(GIT_DESCRIBE "unknown")
set(GIT_BRANCH "unknown")
set(GIT_DIRTY "")
if(Git_FOUND OR GIT_FOUND)
  if(NOT GIT_EXECUTABLE)
    set(GIT_EXECUTABLE git)
  endif()
  execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SRC} rev-parse --short=12 HEAD
                  OUTPUT_VARIABLE GIT_HASH OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SRC} rev-parse --abbrev-ref HEAD
                  OUTPUT_VARIABLE GIT_BRANCH OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SRC} status --porcelain --untracked-files=no
                  OUTPUT_VARIABLE GIT_STATUS OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(NOT "${GIT_STATUS}" STREQUAL "")
    set(GIT_DIRTY "-dirty")
  endif()
  execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SRC} describe --always --tags --dirty
                  OUTPUT_VARIABLE GIT_DESCRIBE OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
endif()
if("${GIT_HASH}" STREQUAL "")
  set(GIT_HASH "unknown")
endif()

if(NOT DEFINED CFG OR "${CFG}" STREQUAL "")
  set(CFG "unknown")
endif()

# NOTE: deliberately NO build timestamp here -- a per-build-changing value would
# rewrite this header every invocation and force a relink each time. Build time is
# taken from the consuming TU's __DATE__/__TIME__ instead (see the fallback in
# logctrl.cpp / inspd_log_main.cpp), so the header only changes on git/config change.
set(CONTENT "// Auto-generated by cmake/gen_build_info.cmake -- DO NOT EDIT.
#pragma once
#define BUILD_GIT_HASH      \"${GIT_HASH}${GIT_DIRTY}\"
#define BUILD_GIT_DESCRIBE  \"${GIT_DESCRIBE}\"
#define BUILD_GIT_BRANCH    \"${GIT_BRANCH}\"
#define BUILD_CONFIG        \"${CFG}\"
")

# Only rewrite when changed, so a stable build doesn't force a relink every time.
set(_old "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" _old)
endif()
if(NOT "${_old}" STREQUAL "${CONTENT}")
  file(WRITE "${OUT}" "${CONTENT}")
endif()
