
export MODULE_logctrl?=$(abspath ../logctrl)

ESS_TRACK= $(wildcard include/*)
IDIR=./include/	$(MODULE_logctrl)/include \
ODIR=obj
_OBJ = MJPEG_Streamer.opp

target_a = MJPEG_Streamer.a

include ../Makefile.in
