

ESS_TRACK= $(shell find include/*)
IDIR=./include/
ODIR=obj
_OBJ = acvImage.opp acvImage_BasicTool.opp acvImage_BasicDrawTool.opp\
 acvImage_MophologyTool.opp acvImage_ToolBox.opp acvImage_ComponentLabelingTool.opp\
 acvImage_SpDomainTool.opp


include ../Makefile.in
