



IDIR=./include/ \
			$(MODULE_cJSON) \
			$(MODULE_acvImage)/include \
			$(MODULE_LOGCTRL)/include

ODIR=obj
_OBJ = VisSeleFeatureManager.opp

target_a= VisSeleFeatureManager.a \
					$(MODULE_cJSON)/cJSON.a \

include ../Makefile.in
