
target_bin = main
IDIR = $(MODULE_cwebsocket)/lib/
VPATH = $(MODULE_cwebsocket)/lib/
_OBJ = main.o websocket.o

ESS_TRACK=
export MakeTemplate:= $(abspath Makefile.in)
export FLAGS= -w -O3
include $(MakeTemplate)
